# Generated by Django 5.0.4 on 2024-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_inventory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('crop', 'crop'), ('tools', 'tools'), ('seeds and chemicals', 'seeds and chemicals')], default='crop', max_length=40),
        ),
    ]
