# Generated by Django 5.0.4 on 2024-04-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_inventory_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='sale_status',
            field=models.CharField(choices=[('on_sale', 'on_sale'), ('not_on_sale', 'not_on_sale')], default='not_on_sale', max_length=40),
        ),
    ]
