# Generated by Django 5.0.4 on 2024-04-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_inventory_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_sales_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
